// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0No7MbE39wHiDMsGWFZn3TCicdcJgFhU',
    appId: '1:199824489046:web:1488aa685f74fec1ba19f7',
    messagingSenderId: '199824489046',
    projectId: 'user-info-d5ed5',
    authDomain: 'user-info-d5ed5.firebaseapp.com',
    storageBucket: 'user-info-d5ed5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLWqRm8t_DRKswa08uHBKmoFiBELiIGYg',
    appId: '1:199824489046:android:5762bcfa474ba3a5ba19f7',
    messagingSenderId: '199824489046',
    projectId: 'user-info-d5ed5',
    storageBucket: 'user-info-d5ed5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANpiVd5qGJbAVeM7N6xNqrYh04enrvm2Q',
    appId: '1:199824489046:ios:5328478d774d0041ba19f7',
    messagingSenderId: '199824489046',
    projectId: 'user-info-d5ed5',
    storageBucket: 'user-info-d5ed5.appspot.com',
    iosClientId: '199824489046-m9ru7fnjh8538hgfn4r83bjcdfpriu33.apps.googleusercontent.com',
    iosBundleId: 'com.example.assign2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANpiVd5qGJbAVeM7N6xNqrYh04enrvm2Q',
    appId: '1:199824489046:ios:5328478d774d0041ba19f7',
    messagingSenderId: '199824489046',
    projectId: 'user-info-d5ed5',
    storageBucket: 'user-info-d5ed5.appspot.com',
    iosClientId: '199824489046-m9ru7fnjh8538hgfn4r83bjcdfpriu33.apps.googleusercontent.com',
    iosBundleId: 'com.example.assign2',
  );
}
